### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by seejamescode** [aholachek/animate-css-grid#1]
Thanks for making this package! I am running into a problem with the following interaction even though I am just toggling the class for `grid-row` and `grid-column`:

Console: `Uncaught TypeError: Cannot read property 'style' of undefined`

![elements](https://user-images.githubusercontent.com/7519029/38842287-c0242bac-41ae-11e8-8390-c6d20afcacab.gif)

![console](https://user-images.githubusercontent.com/7519029/38842288-c0398d4e-41ae-11e8-828e-ad28b68d2d9b.gif)

**Comment by aholachek** [comment]
Hi @seejamescode,
Thank you so much for this bug report! 
I just published version 0.4.5 which should hopefully fix the problem.

**Comment by seejamescode** [comment]
Beautiful
