### ISSUE TITLE
overflow-x causes odd behaviours

### ISSUE THREAD

**Issue by chrisui** [aholachek/animate-css-grid#10]
My issue is demonstrated in the following codepen. If you scroll somewhere within the content and then trigger an animation it seems to get confused (animate from scroll 0) but resolve itself. If you don't change the scroll position again and trigger the changes it seems happy. Scroll again, trigger an animation and, boom, you see the issue again. My guess is there's some internal caching going on which isn't accounting for scroll positioning?

https://codepen.io/anon/pen/RdGVow

My use case is I'm building a timeline view on top of a css grid. Timelines are infinitely long along x axis and therefore need scrolling. I could make the parent scrollable however some columns need to be sticky and due to sticky's relationship with it's parent container it needs to be the grid itself which is scrollable (ie. `overflow-x: auto`).

I'd be happy to look into a fix if I could get some pointers on where to start looking in the code! :)

Ps. Thanks for the library! Was great to drop in to my app so easily.

**Comment by aholachek** [comment]
Hi Chris,
I'm not sure why this is happening, [in the code I'm not currently listening to scroll at all](https://github.com/aholachek/animate-css-grid/blob/master/src/index.ts#L49), just caching each position relative to the top left. That seems to work ok for vertical scroll but clearly something's off with horizontal scroll. I'll look at it tonight, but please feel free to poke around the code and let me know if you find any solution.

**Comment by chrisui** [comment]
Hey Alex,

Thanks so much for the quick investigation!

This does appears to fix the codepen. Is there a way I can test your change with my local codebase?

**Comment by aholachek** [comment]
If you install `animate-css-grid@beta` I think it should download the test version (or you could try directly using v `1.4.0-1`)

**Comment by chrisui** [comment]
Perfect. Have tested and my issue is resolved with `@beta`!

Thanks again for the quick resolution. :)

**Comment by aholachek** [comment]
And thank you for making the issue and testing so quickly! I'll comment here when the patch version is live.

**Comment by aholachek** [comment]
It's been published in v1.40. I removed the necessity to add an option, it should just work if you update the version with no other code changes. Please let me know if anything is still acting weird.
