### ISSUE TITLE
Add plain simple js file

### ISSUE THREAD

**Issue by msdobrescu** [aholachek/animate-css-grid#12]
Hello, please provide a simple javascript file to be included in any html and run, without the need of making bundles, or other stuff.

**Comment by msdobrescu** [comment]
I have done my sample, I could use main.js, removed the map, it is a local html for now.
Being a typescript total newbie and needing this feature without node or typescript at all, what I don't understand is that it needs some more than popmotion. It seems to need throttle and framesync (as it is in src/index.ts), but the resulted js uses popmotion only? How is that?

**Comment by aholachek** [comment]
Hi, sorry for the delay in reply.
You can include via a script tag like this:
`<script src="https://unpkg.com/animate-css-grid@latest"></script>`
