### ISSUE TITLE
Fade out and fade in?

### ISSUE THREAD

**Issue by msdobrescu** [aholachek/animate-css-grid#13]
Is it possible to add fade out and fade in effects for elements going to be hidden/removed and shown/added?
On the github samples there are fade-in classes, but they don't seem to be used. What is their purpose?

**Comment by aholachek** [comment]
Hi, right now the library doesn't handle enter or exit animations, so you would have to manage those yourself. It could be as simple as adding a keyframe `fade-in` animation to the element so that when it appears, the animation happens automatically.
