### ISSUE TITLE
Can't import with Webpack

### ISSUE THREAD

**Issue by aminta** [aholachek/animate-css-grid#15]
`import { wrapGrid } from 'animateCSSGrid';`

gives:

`[12:42:04] Error in plugin 'webpack-stream'
Message:
    ./src/js/app.js
Module not found: Error: Can't resolve 'animateCSSGrid' in '/Users/davide/Sviluppo/Siti Web/Aikido/webstarter-dev/src/js'
resolve 'animateCSSGrid' in '/Users/davide/Sviluppo/Siti Web/Aikido/webstarter-dev/src/js'`

So I set the correct path as from npm install:

`import { wrapGrid }  from 'animate-css-grid';`

No error in compiling, but this error in console:

`TypeError: t is null`

WebPack config:

`let webpackConfig = {
    plugins: [
        new webpack2.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        }),
        new webpack2.optimize.CommonsChunkPlugin({

            name: ['jquery'],
            // (the commons chunk name)

            filename: "vendors.js",
            // (the filename of the commons chunk)

            minChunks: 3,
            // (Modules must be shared between 3 entries)

            /*chunks: ["app", "fullpage", "carousel", "carousel_essenza"],*/
            // (Only use these entries)
        })
    ],
    module: {
        rules: [
            {
                test: /.js$/,
                use: [
                    {
                        loader: 'babel-loader'
                    }
                ]
            }
        ]
    }
}`

**Comment by aholachek** [comment]
Hi, thank you for making this issue! The docs were definitely wrong as you pointed out, I've updated that line to read `import { wrapGrid } from 'animate-css-grid'`. However, not sure what's going on with the second error you pointed out, `TypeError: t is null`. I made a code sandbox [here](https://codesandbox.io/s/4bvq9) to test es6 imports in webpack and it's working fine, so I assume there is some unrelated problem.
