### ISSUE TITLE
Items fly-in from top-left of body, not grid-container

### ISSUE THREAD

**Issue by bramus** [aholachek/animate-css-grid#2]
Hi,

I'm using animated-css-grid to animate a grid that has filtering applied. Items that match the filter stay in place (and slide onto their new position), whilst items that don't match the filter get removed (using `display: none`).

When removing items all works fine: the items that remain in place neatly shift positions.
However, when removing the filter I notice that the items which need to be re-added _(because they got removed in the previous step)_ now fly in from the top-left of the `body` element.

In this scenario I expected them to fly-in from the the top-left of the wrapping grid element (or at least the first parent that has `position: relative` applied), and not the `body`.

I've re-created this filtering effect in this pen:

[![toggle-animation](https://user-images.githubusercontent.com/213073/41511941-f74a2c64-7280-11e8-9656-df32f52c60b2.gif)](https://codepen.io/bramus/pen/xzPPRj)

Look closely at the top left corner of the page as the green items get removed and then re-added.

Is there a better way to do filtering?
If not: can the animation be adjusted to start relative to the container?

Regards,
Bramus!

**Comment by bramus** [comment]
As a workaround I've found a solution where I don't faux-remove the green items (using `display: none`), but move them to the back of the grid (using `order`). Add in some `opacity` changes and you'll get a result that's "good enough".

Demo: https://codepen.io/bramus/pen/BVmmVK

A fix where the items fly in relative to the container would still be something I'd like to request though ;)

**Comment by aholachek** [comment]
Thank you so much for the detailed report, this was super helpful in tracking down the problem.
It's a pretty easy fix, I will publish it later tonight or tomorrow morning and comment here when it's live.

**Comment by aholachek** [comment]
Ah ok, [as you can see in this pen](https://codepen.io/aholachek/pen/NzzNew) I think I've fixed it in version 1.0.4

Thanks again for the report -- please let me know if you still have any problems.

**Comment by bramus** [comment]
Looks fixex indeed. Thanks for this (fast) change 👍
