### ISSUE TITLE
Vue example

### ISSUE THREAD

**Issue by sustained** [aholachek/animate-css-grid#22]
This is cool, good work and thank you.

But I use Vue and not React.

If I create a Vue version of the React example CodePen will you accept a P/R to add it to the README?

**Comment by sustained** [comment]
https://codepen.io/sustained/pen/Rwbdgob

**Comment by Redmern** [comment]
He i cant figure out if its possible to make and animation on gird-areas? like so:

.wrapper {
    height: 100vh;
    margin: 0;
    display: grid;
    grid-template-columns: 4em 1.5em auto 1.5em;
    grid-template-rows: 5em auto;
    grid-template-areas:
        "aside left header right "
        "aside left main   right"
    ;
}

TO

.expanded {
    grid-template-columns: 10em 1.5em auto 1.5em;
  
}

Can you help me with this pls?
