### ISSUE TITLE
Not working on Blazor.

### ISSUE THREAD

**Issue by AdrianoFSilva1** [aholachek/animate-css-grid#24]
So I tried to do this example in my blazor project but it doens't work. I debbuged the JS and the query, to find the element with class .grid, returns null. Im not sure if it is the problem. Here you have a [BlazzorFiddle](https://blazorfiddle.com/s/amlzb6yg) showing that its not working. Thank you for your attention.

**Comment by aholachek** [comment]
I'm going to close this since I lack the knowledge of Blazor to attempt to debug. I would definitely check out a pr to fix though.
