### ISSUE TITLE
jerky text on resize.

### ISSUE THREAD

**Issue by andreElrico** [aholachek/animate-css-grid#35]
I played around I little bit with the library in angular.

Somehow when a grid-item is resized the content (in this case text) is "jerking" a little bit

// tested in ff and chrome,

example: (push the buttons)

https://stackblitz.com/edit/css-grid-animation

------------------------

Ps: Im impressed by this library!

**Comment by andreElrico** [comment]
Solved!

https://stackblitz.com/edit/css-grid-animation-yz7ktv?file=src/app/app.component.ts

If I wrap the text-node into its own DIV its not jerky anymore.

From official DOCS

> 2. Important If a grid item has children, they should be surrounded by a single container element. This is so we can apply a counter scale and prevent children elements from getting warped during scale transitions of the parent.

That was exactly the case here. The scaling created the jerkyness, by wraping it into a div (block element, did not work with span) its decoupled and works as expected.

**Comment by jamesfacts** [comment]
Thanks for this, @andreElrico ! A huge help.
