### ISSUE TITLE
Convert project to ES Module

### ISSUE THREAD

**Issue by de-dan** [aholachek/animate-css-grid#74]
Angular compiler gives a warning about optimization bailouts.

category.component.ts depends on 'animate-css-grid'. CommonJS or AMD dependencies can cause optimization bailouts.

This is currently not a bug, but for the sake of maintainability and a sign of life, this library should be updated :)

I would do this by myself, but I'm stupid.

**Comment by aholachek** [comment]
Sorry for the very slow response, I've just published [v1.5.1](https://github.com/aholachek/animate-css-grid/releases/tag/v1.5.1) which should add the requisite es module.

also lol: 
> I would do this by myself, but I'm stupid.
